In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [16]:
# Categorizing data into X and y
X_train = train_df.drop(columns=["loan_status"])
y_train = train_df["loan_status"]
X_test = test_df.drop(columns=["loan_status"])
y_test = test_df["loan_status"]

In [17]:
# Converting categorical data into numeric data
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()
lbe.fit(y_train)
y_train = lbe.transform(y_train)
print(y_train)
lbe.fit(y_test)
y_test = lbe.transform(y_test)
print(y_test)

[1 1 1 ... 0 0 0]
[1 1 1 ... 0 0 0]


In [19]:
# Creating dummies for categorical data and converting it into numerical data
X_train_dummies = pd.get_dummies(X_train)
X_test_dummies = pd.get_dummies(X_test)

In [41]:
# Test dataset has no 0 Value for debt settlement flag
X_test_dummies.debt_settlement_flag_N.unique()

array([1], dtype=uint8)

In [43]:
# Creating a list of 0 of the same length as the test dataset
zeros = [0] * len(X_test_dummies["debt_settlement_flag_N"])

In [46]:
# Adding the required column to the test dataset
X_test_dummies["debt_settlement_flag_Y"]= zeros

In [53]:
# Confirming that both datasets have the same columns
print(len(X_test_dummies.columns))
print(len(X_train_dummies.columns))

94
94


In [ ]:
# add missing dummy variables to testing set

In [ ]:
# Train the Logistic Regression model on the unscaled data and print the model score

In [ ]:
# Train a Random Forest Classifier model and print the model score

In [ ]:
# Scale the data

In [ ]:
# Train the Logistic Regression model on the scaled data and print the model score

In [ ]:
# Train a Random Forest Classifier model on the scaled data and print the model score